version: '3.9'

services:

  app:
    image: hms_app
    container_name: hms_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hms_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend

  db:
    image: mysql:8.0.31
    container_name: homesuppliesmonitor_db
    volumes:
      - db_homesuppliesmonitor_data:/data/db
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: hms_db
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  db_homesuppliesmonitor_data:

networks:
  backend: