version: '3.9'

services:
 db:
   image: mysql:8.0.31
   container_name: homesuppliesmonitor_db
   volumes:
     - db_homesuppliesmonitor_data:/data/db
   restart: always
   environment:
     MYSQL_USER: IUFqAbDRPcHv
     MYSQL_PASSWORD: obHfmToFEnBa
     MYSQL_ROOT_PASSWORD: obHfmToFEnBa
     MYSQL_DATABASE: hms_db
   ports:
     - "3306:3306"
   networks:
     - backend

volumes:
  db_homesuppliesmonitor_data:

networks:
  backend: